### ISSUE TITLE
No language plugins found

### ISSUE THREAD

**Issue by autarchprinceps** [aws-cloudformation/aws-cloudformation-rpdk#355]
Whenever I try to do a cfn init, I just get "no language plugins found". I have installed rust, python, scala and nodejs however. Increasing verbosity doesn't give me any more details either
```
╰─ cfn init -v    
Initializing new project
What's the name of your resource type?
(Organization::Service::Resource)
>> Test::Test::Test
No language plugins found

aborted

```

**Comment by wbingli** [comment]
Have you installed any language plugin? e.g. Java plugin,  `pip3 install cloudformation-cli-java-plugin`

**Comment by jotompki** [comment]
Hi, if you look at the pypi pages for those languages, they are all in the planning phase. Currently the [java](https://pypi.org/project/cloudformation-cli-java-plugin/) and [go](https://pypi.org/project/cloudformation-cli-go-plugin/) plugins are functional, and the python plugin is a developer preview. You can check that out [here](https://github.com/aws-cloudformation/aws-cloudformation-rpdk-python-plugin/)

**Comment by rjlohan** [comment]
@jotompki - let's update the `README.md` for this repo to explicitly call out the available language plugins and their development status in a little table. That'll help reduce confusion.
